services:
  - type: worker
    name: save-restricted-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: DB_URI
        sync: false
      - key: DB_NAME
        value: SaveRestricted2
      - key: ADMINS
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: ERROR_MESSAGE
        value: "false"
      - key: KEEP_ALIVE
        value: "true"
